spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_com_jpa
    username: staff
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

string:
  from:
    props: string-from-props
  as:
    list: a,b,c
